<?php
// api/verify-token.php
header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST');
header('Access-Control-Allow-Headers: Content-Type');

$TOKENS_FILE = __DIR__.'/../tokens.json';   // generated by generate_tokens.py

if (!file_exists($TOKENS_FILE)) {
    http_response_code(500);
    echo json_encode(['ok'=>false, 'message'=>'Token list not found']);
    exit;
}

$tokenMap = json_decode(file_get_contents($TOKENS_FILE), true); // token => name

$input = json_decode(file_get_contents('php://input'), true);
$token = trim($input['token'] ?? '');

$foundName = null;
foreach ($tokenMap as $t => $name) {
    if ($t === $token) {
        $foundName = $name;
        break;
    }
}

if ($foundName) {
    echo json_encode(['ok'=>true, 'name'=>$foundName]);
} else {
    http_response_code(401);
    echo json_encode(['ok'=>false, 'message'=>'Invalid token']);
}
?>